### ISSUE TITLE
Jobs will not support populating container names, we need to support that

### ISSUE THREAD

**Issue by containscafeine** [kedgeproject/kedge#113]
The way we auto populate container names, we should be able to do that when jobs are implemented. Currently, in kubernetes.go, it is tied to `app.PodSpec.Containers`, we need to generalize that.

Basically abstract this out for jobs -
https://github.com/kedgeproject/kedge/blob/master/pkg/transform/kubernetes/kubernetes.go#L386-L397

**Comment by surajssd** [comment]
>Basically abstract this out for jobs -
https://github.com/kedgeproject/kedge/blob/master/pkg/transform/kubernetes/kubernetes.go#L386-L397 

shows some random thing, maybe tag the link with a commit

**Comment by containscafeine** [comment]
@surajssd -
```golang
	// if only one container set name of it as app name
	if len(app.PodSpec.Containers) == 1 && app.PodSpec.Containers[0].Name == "" {
		app.PodSpec.Containers[0].Name = app.Name
	} else if len(app.PodSpec.Containers) > 1 {
		// check if all the containers have a name
		// if not fail giving error
		for cn, c := range app.PodSpec.Containers {
			if c.Name == "" {
				return nil, fmt.Errorf("app %q: container name not defined for app.containers[%d]", app.Name, cn)
			}
		}
	}


```

**Comment by surajssd** [comment]
this should happen in the fix.go with everything else

**Comment by surajssd** [comment]
This will work because the pod spec in jobs will be our own `PodSpecMod` so the naming thing will be taken care of there.

**Comment by surajssd** [comment]
This is invalid issue, since it does not hold true also job support has been added!

**Comment by surajssd** [comment]
Since https://github.com/kedgeproject/kedge/pull/253 is merged closing this one!
