### ISSUE TITLE
Jobs do not support activeDeadlineSeconds

### ISSUE THREAD

**Issue by containscafeine** [kedgeproject/kedge#114]
Jobs do not support `activeDeadlineSeconds` in JobSpec or PodSpec, we need to fix that.

Blocked on #111

**Comment by surajssd** [comment]
@containscafeine can you confirm is this is valid still ?

Since https://github.com/kedgeproject/kedge/pull/253 is merged I think this is right time to close this one?

**Comment by containscafeine** [comment]
Yes, #253 closes this.
