### ISSUE TITLE
Defining secrets

### ISSUE THREAD

**Issue by containscafeine** [kedgeproject/kedge#128]
Currently, we do not support defining a new secret in the spec. It's one of the most pressing features IMO.

We should add a top level field for this like "ingresses", etc, and also add support for the same in current implementation of envFrom (tracked at #85).

**Comment by containscafeine** [comment]
We decided to wait for user feedback before implementing this right now, but this is definitely on the radar.

**Comment by kadel** [comment]
Even if we are not going to do anything with secrets yet, we should add documentation explaining how to work with secrets in a little bit more complicated way :-)

**Comment by surajssd** [comment]
@kadel The docs are present on how you can use secret, find it [here](https://github.com/kedgeproject/kedge/tree/d105270316552d8fc11397cd329cda63ed7d6ae6/examples/secrets).

**Comment by kadel** [comment]
After discussion last week this changed a little bit.

If we are going to do https://github.com/kedgeproject/kedge/issues/164

Than we can add secrets in the same way as what we have configMaps.
