### ISSUE TITLE
New "tagline"

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#134]
We have:
`Compose Kubernetes apps using Kubernetes constructs`

As the title

and
`Concise Application Definition for Kubernetes`

as the main descriptor.

Could we perhaps come up with a better tagline to entice users to use Kedge?

Perhaps:

`Compose simple and easy-to-use Kubernetes applications`

and

`Compact/Condensed Application Definitions for Kubernetes`

It's hard to come up with names. But usually the "title" (the one one GitHub) is what people are going to see when they search for projects and the other title (in the README) would be more "formal".

**Comment by kadel** [comment]
can we avoid word compose?

**Comment by pradeepto** [comment]
> We have:
Compose Kubernetes apps using Kubernetes constructs

Not anymore. I had changed it some time back. At least I see this -  _" Kedge - Concise Application Definition for Kubernetes"_. Both in the title at the top and in the main readme. This explanation is correct and sounds nice.

I would definitely like to avoid the word "compose". I think the word "concise" is definitely better than "condensed" and perhaps even "compact".

**Comment by kadel** [comment]
I'm quite happy with "Concise Application Definition for Kubernetes" it is short, and I think it describes kedge well.

**Comment by cdrage** [comment]
I saw the title change. :+1: Let's close this since it's been updated. :100:
