### ISSUE TITLE
Make kedge.yaml as the default file

### ISSUE THREAD

**Issue by containscafeine** [kedgeproject/kedge#147]
Thinking about https://github.com/kedgeproject/kedge/issues/96#issuecomment-314418866, does it make sense to have a default filename to look for when we run any kedge command?
Like, `kedge generate` will look for `kedge.yaml` in the current working directory.
Thoughts?

**Comment by kadel** [comment]
Not sure about that.
Don't know if it makes sense when using  "one file=one app" approach. And we agreed that by default we will guide users to this path.

**Comment by pradeepto** [comment]
> Don't know if it makes sense when using "one file=one app" approach. And we agreed that by default we will guide users to this path.

Brilliant point. Had totally missed that angle. Thanks @kadel

**Comment by containscafeine** [comment]
Closing in agreement with @kadel
