### ISSUE TITLE
Is mention bot providing any value?

### ISSUE THREAD

**Issue by kadel** [kedgeproject/kedge#159]
Do you think that mention bot is useful?

I feel like it's not adding any value. Most of the commits are done by 4 people If I look at the comments made by bot, it almost always mentions all of us.

I don't think for a project of our size and stage.

**Comment by cdrage** [comment]
It helps without having to constantly ping people in the initial message.
But otherwise, yes, it's similar people each time.

**Comment by cdrage** [comment]
We can disable the bot for now until we have more users contributing :+1:

**Comment by kadel** [comment]
Can we maybe set it so it ping only one person?

**Comment by cdrage** [comment]
@kadel Yup, PR #161 here

**Comment by surajssd** [comment]
Can we close this one @kadel @cdrage  if the issue is resolved?

**Comment by kadel** [comment]
That bot still doesn't bring me any benefits. Am I alone in this? 
Does it actually help someone?

**Comment by cdrage** [comment]
Pings the correct people, it's helped (ish) with Kompose. I've gone ahead disable it @kadel 

Let me know if people want it enabled again!

**Comment by cdrage** [comment]
Since I've disabled this, i'm going to close the issue! Let's stick with GitHub
