### ISSUE TITLE
Add curl commands to download binaries

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#162]
If you download the binaries now we get the binary with name of os and arch in it for e.g. `kedge-linux-amd64`, we can have a single curl command to download the binary and rename it.

Having this in readme helps me with downloading it by copying the command.

**Comment by containscafeine** [comment]
@surajssd +1, and also move to to somewhere in $PATH

**Comment by cdrage** [comment]
PR #165 fixes this.

**Comment by surajssd** [comment]
#165 is merged so closing it!
