### ISSUE TITLE
kedge should read input from stdin

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#183]
With the above requirement following should be possible

```
echo '...' | kedge generate -f -
```

---
OTOH, with the whole thing about enforcing different apps in separate files, should we support this? Generally reading input from stdin is when you have one huge file for everything and we are not supporting that way of doing things.

WDYT @kadel @cdrage @containscafeine

**Comment by kadel** [comment]
> OTOH, with the whole thing about enforcing different apps in separate files, should we support this?

Why not? You can deploy a single application using this.

We can do this.

But this is low priority for now. We need to solve bigger problems that we are facing.

**Comment by surajnarwade** [comment]
I will take this up

**Comment by kadel** [comment]
> I will take this up

We don't need to worry about this right now its is low priority
