### ISSUE TITLE
Validate the output using kubeval as part of functional tests

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#184]
We can use [kubeval](https://github.com/garethr/kubeval) to validate what is generated by kedge. This will help us to make sure we output correct output.

Now kubeval can be used as a [golang library](https://github.com/garethr/kubeval/blob/e6429b13e13d92424b22b91457b34adafa0c296f/README.md#library).

**Comment by surajssd** [comment]
cc: @surajnarwade maybe this would be of interest to you!

**Comment by surajnarwade** [comment]
Definitely

**Comment by surajnarwade** [comment]
since we have validation for input file now, still we need output file validation.

**Comment by surajssd** [comment]
I don't think so!
