### ISSUE TITLE
"Introduce root level `controller` field", and sub tasks

### ISSUE THREAD

**Issue by containscafeine** [kedgeproject/kedge#188]
This is a result of our very beloved #119 

We need the following changes done -
- [x] Introduce a new optional field "controller" at the root level of the spec which defaults to "deployment"
- [x] Implement unmarshalling based on the "controller" field, e.g. if `controller: deployment` then unmarshal to struct A, and if `controller: job`, then unmarshal to struct B
- [x] refactor jobs PR to accommodate this behavior #116

Let's see how this goes :ghost:

**Comment by kadel** [comment]
> Implement unmarshalling based on the "controller" field, e.g. if controller: deployment then unmarshal to struct A, and if controller: job, then unmarshal to struct B

Is there a simpler solution? Is Kubernetes doing this the same way?

**Comment by surajssd** [comment]
+1 for looking at how k8s does it!

**Comment by containscafeine** [comment]
I found the following in Kubernetes' code -
```golang
func (s unstructuredJSONScheme) Decode(data []byte, _ *schema.GroupVersionKind, obj runtime.Object) (runtime.Object, *schema.GroupVersionKind, error) {
	var err error
	if obj != nil {
		err = s.decodeInto(data, obj)
	} else {
		obj, err = s.decode(data)
	}

	if err != nil {
		return nil, nil, err
	}

	gvk := obj.GetObjectKind().GroupVersionKind()
	if len(gvk.Kind) == 0 {
		return nil, &gvk, runtime.NewMissingKindErr(string(data))
	}

	return obj, &gvk, nil
}
```

So, first all of the unmarshalling is done and then they check if `len(gvk.Kind) ==0`, and if so, return the error.

Will see how to move forward with this information.

**Comment by surajssd** [comment]
Since https://github.com/kedgeproject/kedge/pull/253 is merged closing this one!
