### ISSUE TITLE
Reference Helm Chart from Kedge file

### ISSUE THREAD

**Issue by kadel** [kedgeproject/kedge#217]
It would be nice to have a way to refer helm charts in the Kedge file.

Chart shouldn't be tied to any given Kedge app. That means it can't be done in the way we are doing secrets or config maps.

But it should be in the way that allows deploying everything together using one `kedge` call.
Charts can have parameters, so we need a way not to define just what chart to deploy but also with what parameters.

Maybe separate file defining what chart to deploy? 

This is just my brain dump on this issue.  Later I will try to make this more concrete defintion.

**Comment by pradeepto** [comment]
We can close https://github.com/kedgeproject/kedge/issues/11

**Comment by kadel** [comment]
> We can close #11

ah :-)

I thought we are going to keep it it was before :-)


I'm going to close this one, and we can continue on #11

**Comment by kadel** [comment]
closed as dup of #11
