### ISSUE TITLE
Rename `extraResources` to `includeResources`

### ISSUE THREAD

**Issue by pradeepto** [kedgeproject/kedge#218]
`extra` has different meaning than what we are trying to convey. Should rename it to `extrernal` which is what I think it is. What do you guys think?

**Comment by kadel** [comment]
I agree that `extra` is not the right word. But `external` seems equally strange to me.

Would it be better to have just `kubernetesResources`?

**Comment by pradeepto** [comment]
But what if they are OpenShift resources?

**Comment by kadel** [comment]
hmm, good point

**Comment by surajssd** [comment]
i think we had lot of discussion on naming this thing, so please come up with a generic name that also conveys the meaning then we can go with it, otherwise IMHO `extraResources` conveys what it does!

**Comment by containscafeine** [comment]
- externalResources
- providerResources
- clusterResources
- mergeResources

**Comment by kadel** [comment]
If you want to rename it that I would go with externalResources. But it kind of sounds like it's something that is external to the application, which doesn't have to be true, as is usually part of the application.

So don't know which one is better externalResources/extraResources. I'm fine with both. For me they are both equally strange :-D

**Comment by pradeepto** [comment]
@kadel @surajssd how about `include` or `includeResources` or `import` ?

Pradeepto

**Comment by pradeepto** [comment]
@kadel @surajssd @containscafeine We discussed this and we came to a conclusion that we will use `includeResources`.
