### ISSUE TITLE
Make controller a field in App struct

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#233]
Right now `controller` is a separate struct:

```go
type Controller struct {
	Controller string `json:"controller,omitempty"`
}
```
see [here](https://github.com/kedgeproject/kedge/blob/5283d948443de4ab7c94006fb360963872b1a217/pkg/spec/spec.go#L84-L86)

We should put it in `App` struct as well because right now looking at the `app` struct it is not possible to make out if `controller` is field in there or not. This will help with the OpenAPI generation of code. So I suggest that we keep the field controller inside the `App` struct as well.

**Comment by kadel** [comment]
I think that this was done like this to make parsing YAML file easier.  Am I right @containscafeine .

When we added `controller` field we basically started accepting multiple different YAML files (each controller has its own structure) and we had to start doing two-pass Unmarshalling ([first](https://github.com/kedgeproject/kedge/blob/61545e4d0f122945eeb012f97a2c42f4b6314a5a/pkg/encoding/encoding.go#L32) and [second](https://github.com/kedgeproject/kedge/blob/61545e4d0f122945eeb012f97a2c42f4b6314a5a/pkg/encoding/encoding.go#L39))

Is there another way to do this?

**Comment by surajssd** [comment]
We can have it like the way it is, just add this field also in `App`, so that the automatic parsing of the `spec.go` works just fine.

**Comment by kadel** [comment]
I'm afraid that it won't be possible, as there will be no `App` struct once #116 gets in.
Check [spec.go](https://github.com/containscafeine/kedge/blob/05d4e1a9b82b7908f8e7c94e1c96ba1d29b6b2c8/pkg/spec/spec.go) in that PR

**Comment by containscafeine** [comment]
@kadel yep, Controller is a separate struct for 2 pass unmarshalling, that's the only way I could find when I looked around :(
But after the refactor, the App struct will be renamed to DeploymentSpecMod, but I'm okay with having this extra Controller field in all the Controller structs like in DeploymentSpecMod, JobSpecMod, etc if it's absolutely required for the OpenAPI stuff, but it will be a no-op field, and we should not be confusing it and using it in place of the Controller.Controller field.
