### ISSUE TITLE
Fix roadmap document

### ISSUE THREAD

**Issue by pradeepto** [kedgeproject/kedge#235]
The roadmap [doc](https://github.com/kedgeproject/kedge/blob/master/ROADMAP.md) is horribly broken. Let's fix it. It gives a vision into the project, it should represent the roadmap and its milestones correctly.

**Comment by cdrage** [comment]
I've updated the ROADMAP in order to reflect that we now use milestones. 

If it's okay with you, I'm going to close this issue @pradeepto !
