### ISSUE TITLE
Add `--distribution` flag

### ISSUE THREAD

**Issue by kadel** [kedgeproject/kedge#245]
We need new `--distribution` flag  for `apply`, `generate`, `create` and `delete` commands.

This flag will control if Kubernetes or OpenShift artifacts should be used.

The flag will have two choices `openshift` or `kubernetes` . Default value if `--distribution` is not  set is `kubernetes`

this is part of the bigger goal #210

**Comment by pradeepto** [comment]
This is being worked on via https://github.com/kedgeproject/kedge/pull/250

**Comment by surajssd** [comment]
Closing via https://github.com/kedgeproject/kedge/pull/250
