### ISSUE TITLE
Add e2e tests for Jobs

### ISSUE THREAD

**Issue by containscafeine** [kedgeproject/kedge#270]
Instead of exposing some ports and checking connection, we need to add different sort of e2e tests for Jobs since the nature of the same is to perform tasks (like population) in cluster for other services to consume, instead of getting exposed themselves.

**Comment by ashetty1** [comment]
We probably should be checking job and pod status for this.

**Comment by cdrage** [comment]
Hey @ashetty1 @containscafeine What's the status on this? I could help if-need-be!

**Comment by ashetty1** [comment]
@cdrage PR here waiting to be merged: https://github.com/kedgeproject/kedge/pull/297

**Comment by surajssd** [comment]
Fixed via https://github.com/kedgeproject/kedge/pull/297
