### ISSUE TITLE
more frequent releases?

### ISSUE THREAD

**Issue by jstrachan** [kedgeproject/kedge#277]
there's already 7 issues fixed since 0.1.0 over a month ago; wonder if we should start doing releases every few weeks when new stuff is added/fixed?

**Comment by kadel** [comment]
Yep. It was a mistake to wait more than a month to do a new release.

The plan is to release every 3 weeks starting today.
0.2.0 release is already scheduled to go out later today.

**Comment by jstrachan** [comment]
awesome thanks!
