### ISSUE TITLE
Auto generate Kedge JSON schema for every PR

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#280]
On every merge of PR we need to update the JSONschema for kedge, right now the JSONSchema resides in https://github.com/kedgeproject/json-schema/tree/master/schema Right now it is done manually, we need to automate it.

So two things need to be done right now:

- [x] Do generation of schema as mentioned in docs [here](https://github.com/kedgeproject/json-schema-generator#doing-it-the-easy-way).
- [x] Push that config to some repo or in some place in repo.
- [ ] Documentation on how json-schema generation works and describing generated files as part of this issue.

**Comment by kadel** [comment]
we could use Bintray for hosting JSON schema similarly to what we are doing with latest builds
https://bintray.com/kedgeproject/kedge/kedge

**Comment by pradeepto** [comment]
@kadel That does make sense to me. Except that I would rather call `master` as `master`. Latest is generally the last released version, at least in most places I see.

**Comment by kadel** [comment]
you are right, 'master' is much better

**Comment by kadel** [comment]
part of this PR should also be documentation on how json-schema generation works and describing generated files

**Comment by surajssd** [comment]
@kadel marked it!

**Comment by surajssd** [comment]
Right now blocked on https://github.com/garethr/openapi2jsonschema/issues/5

Will have to debug our OpenAPI maybe if that is causing problems!

**Comment by containscafeine** [comment]
I think our JSON Schema is in a better and workable state right now. All that's left is to do the generation on every merge and push to https://github.com/kedgeproject/json-schema automatically.
