### ISSUE TITLE
Generated Kubernetes Job should default to "restartPolicy: OnFailure"

### ISSUE THREAD

**Issue by containscafeine** [kedgeproject/kedge#290]
I just created a job using the following kedge file -

```yaml
controller: job
name: adduser
containers:
- image: containscafeine/python-gitlab-job-demo:latest
```

But I got the following error -

```console
$ kedge create -f add-user-job.yml 
The Job "adduser" is invalid: spec.template.spec.restartPolicy: Unsupported value: "Always": supported values: OnFailure, Never
kubectl error: failed to execute command: exit status 1
```

I fixed it by specifying the restartPolicy explicitly, but does it make sense to auto populate `restartPolicy: OnFailure` by default?

**Comment by surajssd** [comment]
I think this makes sense, that we create a job with restart policy as `OnFailure`, looking at the behavior of `kubectl run ...` for some inspiration I found that if you specify flag `restart OnFailure` to `kubectl run ...` then it creates job instead of `Deployment`.

See official docs: https://lukemarsden.github.io/docs/user-guide/kubectl/kubectl_run/

**Comment by kadel** [comment]
+1 for `OnFailure` but it has to be well documented, as it differs from Kuberentes default.
If I remember correctly Kubernetes always defaults `restartPolicy` to `Always` even for Jobs.

**Comment by kadel** [comment]
removing the bug, as it is not a bug, it is the same behavior as Kubernetes.

**Comment by mohammedzee1000** [comment]
Hey, i wish to pick up this issue, if that is ok.

**Comment by containscafeine** [comment]
@mohammedzee1000 sure thing

**Comment by surajssd** [comment]
@mohammedzee1000 did you have any progress with this one? Do you need help with this then please ping !

**Comment by cdrage** [comment]
@surajssd @mohammedzee1000 any progress on this? let's pick this back up

**Comment by surajssd** [comment]
@cdrage https://github.com/kedgeproject/kedge/pull/347
