### ISSUE TITLE
add support for `kedge update`

### ISSUE THREAD

**Issue by surajnarwade** [kedgeproject/kedge#293]
kedge should have option to update or should prompt that latest version is available like minishift or gofabric8.

something like, 

```
kedge update
```

For Reference minishift has,

```
minishift update -h
Checks for the latest version of Minishift, prompts the user, and updates the binary if the user answers 'y'.

Usage:
  minishift update [flags]
```

or gofabric8 has,

```
gofabric8 upgrade -h
Upgrades the packages if there is a newer version available

Usage:
  gofabric8 upgrade [name] [flags]
```

**Comment by containscafeine** [comment]
+1, we could also do this like -
`kedge get-versions` returns all the releases available on GitHub.
`kedge update` updates to the latest available release.
`kedge update --version xx.xx` updates to the specific release.
`kedge update --version master` updates to the master binary.

**Comment by surajssd** [comment]
we might need to have `sudo` in some cases

**Comment by cdrage** [comment]
:-1: 

Cons:
 - I have effectively not seen any other tool use this functionality other than `minishift`
 - This command will confuse users who are used to the `kubectl update` command
 - Requires sudo privileges / it replaces binaries
 - Could introduce a host of security issues (man-in-the-middle attacks, URL spoofing for binaries)

I'm voting a hard no.

I'd rather notify the user that there is a new version available and point them to https://github.com/kedgeproject/kedge/releases where the command is to download the binary. Similar to what `minikube` when you run `minikube start`.

**Comment by surajssd** [comment]
>This command will confuse users who are used to the `kubectl update` command

:+1:

**Comment by kadel** [comment]
I personally, don't like this functionality.
Updates and notification about new version should be handled by some package management tool like dnf, apt, brew, chocolatey etc..

**Comment by surajnarwade** [comment]
Agreed with @kadel , Closing this  issue :)
