### ISSUE TITLE
Test the `kedge build` functionality

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#308]
Once https://github.com/kedgeproject/kedge/pull/295 is merged, write tests to see if the `kedge build` functionality is valid.

TODO:

- [ ] See if the image is built 
- [ ] See if the image is pushed to docker registry 

Above things will be again done by using docker client libs

**Comment by ashetty1** [comment]
Picking this up if nobody is working on it yet.

**Comment by ashetty1** [comment]
Picking this up if nobody is working on this yet.

**Comment by ashetty1** [comment]
@surajssd How do you think we should manage the authentication bit for pushing images in test scripts. Any ideas?

**Comment by surajssd** [comment]
@ashetty1 maybe spin up a local docker registry and then try to push the image to that registry?

**Comment by ashetty1** [comment]
@surajssd have something like this now: https://gist.github.com/ashetty1/7f8f3832bebae9f9bcdf50466c6fadd0

Where would you like to have it reside?

**Comment by surajssd** [comment]
@ashetty1  

> Where would you like to have it reside?

I think along with e2e tests

Please send a PR that way it is easier to check and test!

**Comment by kadel** [comment]
@ashetty1 what is state of this?

**Comment by ashetty1** [comment]
@kadel reviews done. Waiting to be merged: https://github.com/kedgeproject/kedge/pull/381

**Comment by kadel** [comment]
closing, as this is done
