### ISSUE TITLE
Update our examples to leverage new kedge shortcuts

### ISSUE THREAD

**Issue by containscafeine** [kedgeproject/kedge#312]
The examples that we have in our repo are not updated to leverage all Kedge shortcuts, etc like portMappings or endpoint or health. We need to update the same.

```
examples/
├── gitlab
├── guestbook-demo
└── wordpress
```

**Comment by surajssd** [comment]
@containscafeine are you working on this? Or who else is working on this one?

**Comment by cdrage** [comment]
@containscafeine @surajssd I've already pushed a PR here: https://github.com/kedgeproject/kedge/pull/435 which is waiting for port mappings to go in: https://github.com/kedgeproject/kedge/pull/455

**Comment by cdrage** [comment]
Assigning this to myself, PR is now unblocked and ready for review at #435

**Comment by cdrage** [comment]
PR merged. Closing.
