### ISSUE TITLE
use oc insetad of kubectl for OpenShift artifacts

### ISSUE THREAD

**Issue by kadel** [kedgeproject/kedge#341]
It is not possible to create OpenShift specific objects with `kubectl`

```
▶ ./kedge apply -f test.yaml
service "nginx" configured
error: error validating "STDIN": error validating data: couldn't find type: v1.DeploymentConfig; if you choose to ignore these errors, turn validation off with --validate=false
kubectl error: failed to execute command: exit status 1
```

For OpenShift artifacts `oc` has to be used instead of `kubectl` when calling `kedge apply`

**Comment by surajssd** [comment]
this should be fixed in https://github.com/kedgeproject/kedge/pull/315 isn't it?

**Comment by containscafeine** [comment]
No, I think this can be a separate PR.

**Comment by containscafeine** [comment]
@kadel added this to the milestone, I think we should fix this to make OpenShift support usable.
