### ISSUE TITLE
Figure out GVK mechanism for OpenShift

### ISSUE THREAD

**Issue by containscafeine** [kedgeproject/kedge#349]
@cdrage pointed out at https://github.com/kedgeproject/kedge/pull/315#discussion_r144059874 that the SetGVK and GetScheme functions only work for Kubernetes, and not for OpenShift. We need to figure out what is the mechanism that OpenShift uses and use that instead of hardcoding the values.
Because hardcoding will not scale once we reach the use case for different Kubernetes/OpenShift versions.

**Comment by surajssd** [comment]
Need to see how kompose is handling it!

**Comment by cdrage** [comment]
@surajssd We specify it manually in TypeObject :100:
