### ISSUE TITLE
add support for openshift in e2e tests

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#375]
Right now we generate openshift configs like `DeploymentConfig` and `Routes`, add tests to e2e test suite to test this.

- We can start using `oc cluster up` openshift cluster to run the test suite
- And then find a way to talk to openshift cluster to query the openshift objects to write the tests for openshift

**Comment by cdrage** [comment]
What's the status on this @ashetty1 I could possible help with this.

**Comment by ashetty1** [comment]
Added as part of #465

**Comment by ashetty1** [comment]
#465 has been merged.
