### ISSUE TITLE
Expand on DeploymentConfig documentation

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#377]
We would like to have an elaborate documentation of what deploymentconfig in this path: [docs/examples/deploymentconfig](https://github.com/kedgeproject/kedge/tree/359a377167b95bdce72134a6f39e63a173c3cc0e/docs/examples/deploymentconfig)

Right now there is just one file which does not mean anything to user landing there. In the same directory we have multiple examples which can show case how to document it there.

**Comment by pradeepto** [comment]
Duplicate of #358
