### ISSUE TITLE
Add version field to the directive and also generate associated metadata based on version

### ISSUE THREAD

**Issue by pradeepto** [kedgeproject/kedge#407]
Here's an example:

```
appversion: 0.3
name: demo
controller: DeploymentConfig
containers:
- image: tomaskral/nonroot-nginx
services:
- portMappings:
  - "8080"
```
Note: `appversion` is just an example, we can have a better name.
Note: Also, this is not kedge version but the application/service version.

This field can be used to generate some kind of annonation metadata that can be used later. e.g 

- `openshift/generated-by:  kedge-init`  
- `openshift/appversion: 0.4`
- `kubernetes/generated-by:  kedge-init`  
- `kubernetes/appversion: 0.4`

Why do we need this? 

- Metadata can be used to retrospect
- The `appversion` field can be used later to add capability to tooling that could possibly pick up a certain version and deploy that.

**Comment by cdrage** [comment]
This'd work with OpenShift Service Catalogs and Helm charts, right?

For example, when creating a Helm chart, it'll populate the `version` section.

Just `version` seems good instead of `appversion` (I know you said it's temporary :+1: )

**Comment by kadel** [comment]
> This'd work with OpenShift Service Catalogs and Helm charts, right?
> 
> For example, when creating a Helm chart, it'll populate the version section.

yes this can be one of the places where it can be used

> Just version seems good instead of appversion (I know you said it's temporary  )

I think that in future will have to start versioning kedge format (probably based on kubernetes api versions). Calling it just version might be confusing and easily mistaken for kedge format version.

This field should indicate Application version (or version of given application definition). `appversion`, `applicationVersion` or something along those lines is more suitable.

**Comment by piyush1594** [comment]
Just a suggestion to keep it appversion, as 'key' we are using for name is 'app' in labels. (Maybe I am wrong). Please let me know the final key name we should keep.

And we want to add the key-value pair in labels or annotations?

**Comment by cdrage** [comment]
IMO appversion should be without quotes `appversion: 0.3` but eventually we will updates `types.go` so we can allow both int and string input similar to #438

**Comment by kadel** [comment]
> IMO appversion should be without quotes appversion: 0.3 but eventually we will updates types.go so we can allow both int and string input similar to #438

@cdrage 
I disagree with this, to be honest. `portMapping` is a different story because that can be a real integer.
But his has to be always a string. If we do this for `appversion` than we should do that for every string field to be consident and that is not feasible.

**Comment by surajnarwade** [comment]
since PR is merged, we can close this issue ?

**Comment by cdrage** [comment]
I believe so :+1:
