### ISSUE TITLE
Add Kubernetes/OpenShift table to file-reference

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#426]
Relates to #413 

Update the file-reference.md document with a table for what *else* can be defined. For example, `service` extends `ServiceSpec`. We should include the following: https://kubernetes.io/docs/api-reference/v1.8/#container-v1-core

**Comment by cdrage** [comment]
Hey @kadel @pradeepto what's your opinion on including the tables?

I was trying to find a way to auto-generate this, but it's a bit difficult to parse all the information through the doc website. Perhaps a simple Go script though (go through each key/value?).

Should we still include the tables or just a simple link to the documentation on the Kubernetes site?

**Comment by surajssd** [comment]
@cdrage this is the hard problem, we need someone from docs team to help on this particular problem.

**Comment by cdrage** [comment]
IMO, including the links to Kubernetes seems like the safest option so-far without the file-reference page getting massively big. But then again, I've only done docs for a short-amount-of-time. We could wait for a professional opinion on getting tables from https://kubernetes.io/docs/api-reference/v1.8/#container-v1-core to kedgeproject.org/file-reference/

**Comment by cdrage** [comment]
Ping @surajssd @kadel what's your opinion? Should we put this in the unfinished milestones as well (until we get a professional opinion)

**Comment by cdrage** [comment]
Just an FYI. After discussions with #565 I would like to take this up. However. I plan to merge both this (Adding Kubernetes tables, etc.) as well as the update to the file structure (#565) in one big PR.
