### ISSUE TITLE
Rename objects

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#427]
Within file-reference.md we have different names for different objects.

For example: http://kedgeproject.org/file-reference/#containerspec

We have containerSpec, service and then.... routeObject.

Names should be consistent.

Either:

containerSpec, serviceSpec, routeSpec

or

containerObject, serviceObject, routeObject

:+1: for Object.

**Comment by cdrage** [comment]
Thoughts @kadel @pradeepto

**Comment by pradeepto** [comment]
Good catch. We should be consistent with our object naming. This is definitely an UX issue.

**Comment by kadel** [comment]
There is a difference between `routeObject` and `routeSpec`

`routeObject` refers to Kedge struct that includes OpenShift's `routeSpec` and `objectMeta`
https://github.com/kedgeproject/kedge/blob/master/pkg/spec/types.go#L78

**Comment by cdrage** [comment]
@kadel Problem is that most people won't be looking at the code-names, but rather the documentation names. Could we refer to it as a routeSpecObject instead within the documentation?

Are you good with the other parts being renamed (containerObject, serviceObject, etc..)

**Comment by kadel** [comment]
We should distinguish between what is referring to our `RouteSpecMod` and what is referring upstream `RouteSpec`. We have to careful and not to interchange them. It can have whatever name but we just can't interchange them.

**Comment by cdrage** [comment]
Hmm. so in the docs, let's go with routeSpecObject? @kadel

**Comment by kadel** [comment]
You are talking about what will be in the sidebar in Objects section, right?

I would actually go with just 'route' and 'ingress'

**Comment by cdrage** [comment]
PR here: https://github.com/kedgeproject/kedge/pull/429
