### ISSUE TITLE
`kedge generate` should create files, rather than go to stdout

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#436]
IMO, `kedge generate` should create files in the root directory. `--stdout` command should be added (or `-o` for short) to output to STDOUT.

**Comment by containscafeine** [comment]
I'd disagree here. I don't think we should be creating files by default. Maybe we could add an `-o` flag to specify a directory or a filename to save the files to.

**Comment by kadel** [comment]
> I'd disagree here. I don't think we should be creating files by default.

agree

> Maybe we could add an -o flag to specify a directory or a filename to save the files to.

I don't think that we should do this.
Purpose of `generate` command is for debugging and advance use cases where you want to pipe it to `kubectl` or `oc`.

Most users should use `apply`.
