### ISSUE TITLE
is it possible to use oc instead of kubectl while doing `kedge create/apply` ?

### ISSUE THREAD

**Issue by pranavgore09** [kedgeproject/kedge#458]
I am running `kedge apply -f filename` and facing following error.
```failed to execute command: failed to execute command: exec: "kubectl": executable file not found in $PATH```

yes, I do not have `kubectl` installed, but is it possible to use `oc` here?

**Comment by containscafeine** [comment]
If the end user does not want to install `kubectl` binary and wants to use `kedge create/apply/delete` commands using `oc`, one hack is to alias `kubectl` to `oc`, and it should work.

Later on, when we'll be moving to `client-go` for Kubernetes and OpenShift, then these binaries won't be required.

However, this is somewhere the end user experience breaks and flags like `--provider kubernetes/openshift` or `--use-oc true/false` could help.

ping @kadel, WDYT?

**Comment by surajssd** [comment]
I think we should fallback to `oc` if `kubectl` not found in path, if nothing found then error out!

**Comment by surajssd** [comment]
Also `oc` can create all objects that kubernetes supports.

I was doubtful of ingress but tried that and it worked:

```console
$ kedge generate -f . | oc create -f -
service "database" created
deployment "database" created
service "wordpress" created
ingress "root-ingress" created
deployment "web" created
```

**Comment by kadel** [comment]
> I think we should fallback to oc if kubectl not found in path, if nothing found then error out!
>  👍 2

Agree this might be the best way how to do that right now.

**Comment by kadel** [comment]
> I am running kedge apply -f filename and facing following error.
> failed to execute command: failed to execute command: exec: "kubectl": executable file not found in $PATH
> 
> yes, I do not have kubectl installed, but is it possible to use oc here?

@pranavgore09 
Are you creating any OpenShift objects, like  DeploymentConfig? Or just Deployment?

**Comment by kadel** [comment]
**TASK**:
Kedge should fallback to `oc` if `kubectl` is not found in path. If `oc` is not found either then error out!

**Comment by debloper** [comment]
As it's already mentioned in the [kedge-docs](http://kedgeproject.org/file-reference/#controller), mentioning the `controller` should ideally be good enough (given, the values were intuitive enough to express the container orchestrators) to invoke the correct tool for the purpose.

I agree, that on a system that has either `kubectl` or `oc` then it's best to not complain about not finding the controller (as long as it's not specifically mentioned) and fall back to the other; but, it should still regard the specific controller selection for hosts which has both `kubectl` and `oc` setup, but wants to use specific one of them for a particular purpose.

**Comment by kadel** [comment]
Yes, `controller` should still be primary indicator.

Only problem is when someone uses OpenShift but and deploys Deployment or Jobs on it. And they don't have `kubectl` installed as they don't need it. 
For this, we should fallback to `oc` if `kubectl` is not found.  But only this. Kedge can **never** do fallback in other direction from `oc` to `kubectl`.

**Comment by tariq-islam** [comment]
The error that is produced due to this "fix" is misleading. In the absence of kubectl the error states: "failed to execute command: Unable to find oc command. Please install oc to your system"

How is this any better? This is just persisting the problem if a user (of which there are many) does not use OpenShift or know what 'oc' is. This is particularly true if kedge is being used in varying CD environments.

This is not an issue at all. The error message clearly states that kubectl is missing from PATH. I don't see this as a bug and I'm not sure why oc was even introduced, especially given that you're now going from a general cli to a specific one.
