### ISSUE TITLE
How to test documentation PR locally ?

### ISSUE THREAD

**Issue by surajnarwade** [kedgeproject/kedge#469]
It's very difficult to try documentation changes and preview locally, any additional documenation will help.

**Comment by containscafeine** [comment]
Do you mean how to test markdown changes locally? There are plugins for IDEs which can help with that.

**Comment by cdrage** [comment]
You can just push the docs to your branch and view it on GitHub.. for example:

https://github.com/cdrage/kedge/blob/documentation-updates/docs/file-reference.md

**Comment by kadel** [comment]
@surajnarwade is probably asking how to generate file-reference webpage locally, right?

It is using https://github.com/lord/slate
You can check [./scripts/sync-doc.sh](https://github.com/kedgeproject/kedge/blob/feb9899909ece478ae6d0c82966a5fd46f3d2784/scripts/sync-docs.sh#L96) to se how its generated for kedgeproject.org webpage

**Comment by cdrage** [comment]
@surajnarwade Right now we generate slate using a docker image. Generating the static build:

docker run --rm -v $PWD:/usr/src/app/source -w /usr/src/app/source cdrage/slate bundle exec middleman build --clean

If you run the above command and then: `jekyll serve .` in the same directory, you should be able to view the docs at `localhost:4000`

I should add a command within the Makefile for this... probably `make serve-docs`

**Comment by surajnarwade** [comment]
@kadel @cdrage cool, thanks :)

**Comment by kadel** [comment]
can we close this?

**Comment by surajnarwade** [comment]
@kadel sure
