### ISSUE TITLE
No documentation on apply / should start using "apply" as a default program.

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#479]
As I'm working my way through the "Kubernetes: Up and Running" book, I see that most, if not, all the default commands use `kubectl apply` instead of `kubectl create`.

Going through the kubernetes.io documentation, you can see that most tutorials also use the apply command: https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/ + https://kubernetes.io/docs/tasks/

We need to do three things:

- Add documentation on the `apply` command
- Add testing on the apply command
- Convert all examples (README's, etc.) to use the apply command.

Not only is `apply` better (checks to see what's already deployed, errors out correctly), it's the default/most-used in Kubernetes.

@kadel @pradeepto

**Comment by kadel** [comment]
Agreed 100%, `apply` should be a default command
