### ISSUE TITLE
Blog about Kedge

### ISSUE THREAD

**Issue by pradeepto** [kedgeproject/kedge#480]
- Write a use case story on how Kedge is used by developer who is developing microservice running on Kubernetes
- How does the developer start the project?
- How does the developer maintain the microservice, how does the developer maintain the kedge files?

We need a common medium account for Kedge.

Please feel free to add more ideas.

**Comment by kadel** [comment]
Important is answer the question why should developer use Kedge

**Comment by cdrage** [comment]
For clarification, should we have this on the main website? Github / PR push-a-able. Or is this more of a generic / overview goal in terms of maintainers / group members posting on Medium, etc. @pradeepto

**Comment by kadel** [comment]
I think that separate blog on medium will give us a slightly bigger exposure than standalone blog on kedge site. Maybe I'm wrong, but I was convinced that medium platform could attract a bit more visitors

**Comment by cdrage** [comment]
@kadel agreed :+1:

**Comment by kadel** [comment]
can ve close this?
blog post has been posted here: https://medium.com/kedge/journey-of-a-developer-developing-on-kubernetes-bdb338dea7b4
