### ISSUE TITLE
Decouple validation from generation code

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#49]
Right now we have validation code and the generator code mixed which is not the good thing I think so think about decoupling it for our own ease of maintaining the project for the long term.

Similar to what we did in OpenCompose we can do it here as well. 

So what I think is that we create a validation function for what we have read in after `app, err := encoding.Decode(data)` in `pkg/cmd/convert.go`. This will pull all the validation code like the case we are checking if multiple containers are given then is the `name` field is provided by the user. And more like those.

**Comment by containscafeine** [comment]
@surajssd can we close this? We have separate validation functions now.
