### ISSUE TITLE
kedge build returns - unable to create a tarball: archive/tar: write too long

### ISSUE THREAD

**Issue by containscafeine** [kedgeproject/kedge#490]
My current directly size is -
```console
$ du -sh
812M    .
```

And I have simple Dockerfile in the current directory -
```console
$ cat Dockerfile 
FROM centos:7
CMD ping
```

Upon running `kedge build -i imagename` I expect a simple image to be built, instead I get the following error -
```console
$ kedge build -i testrun
INFO[0000] Building image 'testrun' from directory 'kedge' 
unable to create a tarball: archive/tar: write too long
```

This error does not occur when the current directory size is small.
I don't think so building an image should be dependent on the size of the current directory.

**Comment by kadel** [comment]
This issue is not caused by size of the directory but because there are symlinks in it!
