### ISSUE TITLE
Specifying default value for Kedge variable

### ISSUE THREAD

**Issue by kadel** [kedgeproject/kedge#491]
Allow specifying a default value for a variable if it is not set.

example kedge file:
```yaml
name: foo
image: foo/bar:[[ TAG:latest ]]
```

If `TAG` variable is not set, it `latest` will be used.

The rule for detecting default value should be: use everything between `:` and `]]` and trim whitespaces from both ends.

**Comment by surajnarwade** [comment]
I will pick this up
