### ISSUE TITLE
Decouple injecting default values from the generation code

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#50]
Building on top of the another issue https://github.com/surajssd/kapp/issues/49 where I talk about removing the validation code from generation code to separate place. Similarly, we need to decouple the code where we are inserting the defaults into separate place so that we can know how defaults get inserted.

**Comment by kadel** [comment]
agreed, I've touched this in https://github.com/surajssd/kapp/pull/37#discussion_r123199418

**Comment by containscafeine** [comment]
@surajssd we have populators now, can we close this?
