### ISSUE TITLE
Gaps in documentation (add getting started guide, update user guide and examples)

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#501]
Some gaps within the documentation at the moment.

 - [x] Need a Getting Started guide in order to facilitate different development scenarios (against bare-metal, minikube, minishift, etc.)
 - [x] Update the User Guide with more information / elaborate on all commands
 - [x] Highlight examples / make examples more prominent within Kedge.

**Comment by cdrage** [comment]
PR for getting started guide added here #508

**Comment by cdrage** [comment]
@kadel Creating something similar to https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands for examples + kedge CLI reference, what do you think?

We will essentially have two slate sections (similar to how they do it within http://kubernetes.io).

My thinking is that by creating a separate one for `kedge` CLI (converting http://kedgeproject.org/user-guide/ to slate) we can also elaborate / focus on examples.

WDYT?

**Comment by pradeepto** [comment]
LGTM

**Comment by cdrage** [comment]
Going to close this :+1: Since I've completely each-task.
