### ISSUE TITLE
Fix portMappings documentation

### ISSUE THREAD

**Issue by kadel** [kedgeproject/kedge#502]
Current documentation of `portMappings` in file reference is really bad.

I don't say what it does and what different parts of the value mean.

We should take some parts from https://github.com/kedgeproject/kedge/tree/master/docs/examples/portMappings and add it to http://kedgeproject.org/file-reference/#serviceobject

**Comment by cdrage** [comment]
Bit confused, it does? http://kedgeproject.org/file-reference/#serviceobject

Scroll down below to portMappings and it's the exact same as https://github.com/kedgeproject/kedge/tree/master/docs/examples/portMappings

**Comment by cdrage** [comment]
Should we close this @kadel ?

**Comment by kadel** [comment]
ok, closing.
