### ISSUE TITLE
Our guestbook example isn't the same as the official example

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#511]
So https://github.com/kedgeproject/kedge/tree/master/examples/guestbook-demo has a description that links to https://kubernetes.io/docs/tutorials/stateless-application/guestbook/

However, both examples differentiate drastically, one uses mariadb, the other one uses redis, as well as custom containers for both examples.

We should either remove the link or make the examples similar in nature :+1:

**Comment by surajnarwade** [comment]
@cdrage , I think we should make examples similar in nature so that any new comer will not feel any difference (as he will be familiar with official kubernetes guestbook example)

**Comment by cdrage** [comment]
@surajnarwade Exactly, hence why our example should follow the same as the official one (using redis, etc.) similar to what you did with Gitlab :+1:

**Comment by surajnarwade** [comment]
@cdrage I would like to work on this :)

**Comment by kadel** [comment]
I don't know how it got there, but the guestbook example that is there is guestbook that I created for some demo while back. 
It has nothing to do with Kubernetes example. Problem whit Kubernetes example is that it doesn't work on OpenShift. So if we want to use that one we will have to modify images so they work without root.

**Comment by cdrage** [comment]
@kadel Could we have two? One that works with Kubernetes and is the exact same as the Kubernetes demo, and another go-to example for OpenShift that uses non-root containers?

**Comment by kadel** [comment]
sure we can. We have to clearly state somewhere in the demo (probably in the readme and also in comments in Kedge file) that given example is not universal, and will only run Kubernetes or on OpenShift with lifted restrictions on root containers.
