### ISSUE TITLE
Incorrect PR number in commit message

### ISSUE THREAD

**Issue by surajnarwade** [kedgeproject/kedge#555]
PR number link is incorrect in commit message to `json-schema` repo which is auto commited for every PR merge for this repo.

```
Commit: kedgeproject/kedge@6c61d45

PR: https://github.com/kedgeproject/kedge/pull/false
```

**Comment by containscafeine** [comment]
Yeah, we should probably remove it since this is only put when the PR has already been merged i.e. it runs only on master. Hence, no PR number.
