### ISSUE TITLE
Test all examples in docs/examples and examples

### ISSUE THREAD

**Issue by kadel** [kedgeproject/kedge#558]
We should make sure that all examples in `docs/examples` and in `examples` can be converted.

We have framework for command line tests (see https://github.com/kedgeproject/kedge/pull/498)

We should add test that will list all YAML files in directories with examples and run `kedge generate` on them.
This will be especially useful for #481

**Comment by kadel** [comment]
related to https://github.com/kedgeproject/json-schema-generator/issues/25

**Comment by kadel** [comment]
we can implement just https://github.com/kedgeproject/json-schema-generator/issues/25 as it is basically the same thing

**Comment by surajnarwade** [comment]
I have implemented this test [here](https://github.com/kedgeproject/kedge/pull/481/commits/f78c5a4ef0b81c473c580be0762a57b342a29c6c#diff-2fd956fb798d519aa017383f8d85c53f) in PR #481

**Comment by surajnarwade** [comment]
Closing this since #481 is merged now and we are testing all examples from `docs/examples` and `examples` here https://github.com/kedgeproject/kedge/blob/master/tests/cmd/cmd_test.go#L136
