### ISSUE TITLE
VSCode integration with LSP

### ISSUE THREAD

**Issue by containscafeine** [kedgeproject/kedge#559]
We have JSON Schema for Kedge at https://github.com/kedgeproject/json-schema
We can integrate with VSCode to introduce auto-completion features, etc by introducing LSP support.

I found some work being done around the same at -
- https://github.com/search?q=org%3Aredhat-developer+kedge

ping @surajssd, can you provide leads on what your findings were when you were looking into this?

**Comment by surajnarwade** [comment]
Closing since we have LSP integration ready :)
