### ISSUE TITLE
Add command line conversion tests

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#58]
$subject. This is type of functional test but we need to have a comparison tests as well.

From metaissue https://github.com/surajssd/kapp/issues/24

**Comment by surajssd** [comment]
We have some fixtures for corner cases in [tests/cmd](https://github.com/kedgeproject/kedge/tree/5de239ca03c1832c0827aed834b5825c4f127601/tests/cmd), we should add code that will run conversion checks like we have in kompose, but let's do this in golang than in bash.

**Comment by ashetty1** [comment]
@surajssd how urgent is this? I'd love to take this up.

**Comment by surajssd** [comment]
@ashetty1 we want this, not sure of the urgency! The most urgent thing we would like to see is a wrapper around e2e tests, that will show what is happening in cluster while e2e tests are running.

**Comment by kadel** [comment]
This needs to be broken down to smaller tasks

**Comment by cdrage** [comment]
https://github.com/kedgeproject/kedge/pull/498 has been merged.
