### ISSUE TITLE
e2e tests - test conversions on running cluster

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#59]
This is again a type of functional test. 

From metaissue https://github.com/surajssd/kapp/issues/24

**Comment by pradeepto** [comment]
Linking https://github.com/kedgeproject/kedge/pull/77 here for reference. cc @surajssd

**Comment by surajssd** [comment]
@cdrage @kadel is there a way we can run minikube or single node k8s cluster on travis ?

**Comment by cdrage** [comment]
@surajssd Yes, you can create a single-node cluster using docker containers (no minikube, since that's virtualization).

See: https://github.com/kubernetes/community/blob/master/contributors/devel/local-cluster/docker.md

as well as https://github.com/projectatomic/adb-tests/blob/master/cdrage-atomicapp-ci/functional-tests/providers/kubernetes.sh

I'm working on adding this to Kompose, I could possibly add this to Kedge as well.

**Comment by surajssd** [comment]
@cdrage minikube has this `vm-driver` called `none`, have tried that it runs as root only, so do you know if travis provides root access.

```bash
$ minikube start -h
Starts a local kubernetes cluster using VM. This command
...
      --vm-driver string                VM driver is one of: [virtualbox kvm none] (default "virtualbox")
...
```

**Comment by kadel** [comment]
> @cdrage minikube has this vm-driver called none, have tried that it runs as root only, so do you know if travis provides root access.

yep, you can run stuff as root on travis

**Comment by cdrage** [comment]
Hey @surajssd @kadel I added this to kompose https://github.com/kubernetes/kompose/pull/731 which uses https://github.com/kubernetes/minikube/tree/master/deploy/docker by Minikube. 

I can open up a PR for this in Kedge as well.

**Comment by surajssd** [comment]
@cdrage Yes that will be helpful!

**Comment by surajssd** [comment]
This is partially done by #77 because it has enabled the tests to run on local running cluster the work to make it working on CI is still remaining!

**Comment by cdrage** [comment]
@surajssd I'll take this up! Will have to add a way to bring up a Kubernetes docker cluster, I'll probably copy scripts from https://github.com/kubernetes/kompose

**Comment by surajssd** [comment]
@cdrage I think this done, we can close this one!
