### ISSUE TITLE
CONTRIBUTING file: add developer notes explaining code layout

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#62]
In this section there will be developer docs, which contains information like how the code base is setup, how the golang struct embedding is important for what we are doing, when we modify a struct how we add the name `mod` at the end of the new struct name, etc.

**Comment by pradeepto** [comment]
@surajssd Can we close this since @cdrage sent a PR for this? https://github.com/kedgeproject/kedge/pull/79

**Comment by surajssd** [comment]
@pradeepto this is not done yet

**Comment by cdrage** [comment]
@surajssd Could you describe what needs to be done?

**Comment by surajssd** [comment]
I am taking this up will try to write up how the data flow happens in there and how the code is structured.

**Comment by surajnarwade** [comment]
@surajssd since #464 is merged, WDYT, what else do we need to add to docs ?
