### ISSUE TITLE
CONTRIBUTING file: add process of PR merging

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#63]
Process of PR merging, things like how many LGTMs does it need to merge a PR, who merges the PR, if PR is open for more than 2weeks what should it be labeled as? How do we break down the big issues, etc.

**Comment by cdrage** [comment]
@surajssd Anything else we need to add to https://github.com/kedgeproject/kedge/blob/master/docs/development.md ? I think I covered it all.

**Comment by cdrage** [comment]
Woops, closed by accident

**Comment by pradeepto** [comment]
@cdrage +1 from me about closing this issue. 

But I am not sure what @surajssd means by "how we break down big issues?". Is it about filing epics and issues? Or is it about sending small PRs per issue?
