### ISSUE TITLE
Create communication channels and update readme etc.

### ISSUE THREAD

**Issue by pradeepto** [kedgeproject/kedge#64]
- [ ] mailinglist
- [ ] chat / slack / irc
- [ ] community meeting times

**Comment by cdrage** [comment]
I have created https://kedgeproject.slack.com for chatting :+1: @pradeepto

**Comment by surajssd** [comment]
@cdrage how do I get invite on this?

**Comment by cdrage** [comment]
@surajssd I will have to set it up with this: https://github.com/rauchg/slackin on a public VPS.

**Comment by cdrage** [comment]
I believe this can be closed @pradeepto as I've updated the README with the required details. How to contribute as well as where we hang-out (slack).

IMO, I wouldn't do a mailing list.. Keep it to GitHub + Slack.

**Comment by kadel** [comment]
+1 for github and slack

- github issues for async communication and all project decisions
- slack for ad-hoc communication 

But all important things should be discussed in github issues or PRs and not on slack, to leave some time for everyone to react (because of different time zones)

**Comment by cdrage** [comment]
@kadel @pradeepto Ideally, slack for now until (possible) merge into Kubernetes Incubator / Kubernetes Slack, see: https://get.slack.help/hc/en-us/articles/201748703-Import-message-history so we won't lose our channel history.

**Comment by pradeepto** [comment]
Great! Closing this.
