### ISSUE TITLE
Add documentation, user guide etc

### ISSUE THREAD

**Issue by pradeepto** [kedgeproject/kedge#65]
- [ ] Comprehensive user guide
- [x] Website? - http://kedgeproject.org/
- [ ] Document how this works, architecture.

**Comment by cdrage** [comment]
Userguide here: #130 
Once merge, site can be created.

**Comment by pradeepto** [comment]
> Once merged as well as a "guickstart" doc is added, the site can be created.

We need a page on the architecture before the website. I think @surajssd is working on it or was supposed to.

**Comment by surajssd** [comment]
@pradeepto we don't need architecture for website, the thing I am working on is more for developers who gonna contribute to kedge

**Comment by cdrage** [comment]
I agree with @surajssd I don't think we need an architecture doc similar to http://kompose.io/architecture/ we're moving too fast that things may be outdated the next week after (including stuff such as openapi that is being added)

**Comment by cdrage** [comment]
What we have so far is a:

- Quickstart
- Userguide
- Development

which I think is enough to start a rudimentary website.

Other docs such as installation should be added too.

**Comment by cdrage** [comment]
Comprehensive user guide as well as an elaborate file reference guide has been added, going to go-ahead and close this :+1:
