### ISSUE TITLE
Update client-go to "3.0"

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#81]
Right now the client-go we use is k8s1.5. We need to update it to get new features.

Read this compatability matrix for client-go which explains what version of client-go supports what version of k8s https://github.com/kubernetes/client-go#compatibility-matrix 

This will unblock me on the e2e tests setup I am doing in https://github.com/surajssd/kapp/pull/77

**Comment by pradeepto** [comment]
Should we not wait until it comes out of Beta? I don't have any strong opinion on this matter, just curious what is the right/pragmatic thing to do?

**Comment by containscafeine** [comment]
@pradeepto that could block us for a long time wrt features.
