### ISSUE TITLE
A better and relevant name for this project

### ISSUE THREAD

**Issue by pradeepto** [kedgeproject/kedge#9]
This is important. Hopefully, the name should highlight the rationale behind this project clearly. 

Some requirements - the name should be: 
- Should be unique, at least in the k8s world.
- Should not conflict with some existing famous project (i.e. adb)
- Should be available on GH (project, org etc)
- Getting a domain is a great advantage

**Comment by surajssd** [comment]
@pradeepto can we close this one ?

**Comment by cdrage** [comment]
I think we can :+1:
