### ISSUE TITLE
flag to deploy to specific namespace

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#93]
Right now `kedge deploy`, deploys to the current namespace that is selected. But it would be awesome to have a flag that we can use to deploy to specific namespace.

Something like following:

```bash
kedge deploy -n foo -f web.yaml
kedge deploy --namespace foo -f web.yaml
```

**Comment by containscafeine** [comment]
ping @kedgeproject/maintainers, are we good with the UX on this before we proceed?

**Comment by cdrage** [comment]
Yup. `--namespace` and `-n` makes sense.

**Comment by containscafeine** [comment]
Do we want to scope specifying namespace using `-n` only to `kedge deploy/apply` or do want it for generate too? `ObjectMeta` has `Namespace string` as a field, so we could substitute it there for the generated artifacts.

Btw, namespace can also be specified in the kedge spec for the application alternatively since it's a part of ObjectMeta.

**Comment by surajssd** [comment]
@containscafeine do we have ObjectMeta? I don't think we have?

**Comment by containscafeine** [comment]
@surajssd totally missed that :) Yeah, so namespace cannot go in the spec the way it is right now.
WDYT about extending this to `kedge generate` as well?

**Comment by surajssd** [comment]
I don't have problem in doing it in `generate`, but it's just that we will have to handle it when we are creating the `ObjectMeta`!

**Comment by kadel** [comment]
I don't think namespace should be there for `generate`. 
I don't like when a namespace is hardcoded in artifacts.

If you are deploying such artifacts you have to be extra careful to deploy it to the right namespace.

**Comment by cdrage** [comment]
I'd agree with @kadel that --namespace should be within create / delete rather than generate (makes no sense there)

**Comment by containscafeine** [comment]
ack
