### ISSUE TITLE
Running `kedge generate/deploy` returns nothing, expected error

### ISSUE THREAD

**Issue by containscafeine** [kedgeproject/kedge#96]
Running plain `kedge deploy` should return an error that no file specified, or something similar but currently it return nothing -

```console
💢concaf kedge (master) $ kedge deploy
💢concaf kedge (master) $ 
```

**Comment by kadel** [comment]
same issue is also with `kedge generate`

**Comment by kadel** [comment]
we should make `-f`/`--file` flag required. If it's not set we show help for given command.

`kedge generate` should display same output as `kedge generate -h` and similarly for `kedge deploy` should display same output as calling `kedge deploy -h`

We should also add a note to  `-f` stating that this flag is required.

**Comment by containscafeine** [comment]
@kadel +1. Once #147 is resolved, will fix this.
