### ISSUE TITLE
abstract out kedge "populators"

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#98]
Take a look at the diagram below:

![download 1](https://user-images.githubusercontent.com/5815795/27681143-d2621102-5cdb-11e7-88f4-caa7e49e4455.jpg)

## Diagram explanation

The left block in `app` with the name `containers[]` is the `containers[]` that we over-ride with our custom fields like `health`, `envFrom`. The right block is the one that is part of `podSpec` that we have over-ridden in the left.

## Problem explanation

We have added certain new fields on top of what is defined in containers spec. And so the data is parsed into these defined fields that are outside like the `containers[]` in `app` gets all the data while the `containers[]` in `podSpec` has no data.

The `containerSpec` has to be copied into the `containerSpec` in `podSpec`. So we have to copy all the data from `app` level `containers[]` to `podSpec` `containers[]`. Also `health` has to be transformed into `livenessProbe` and `readinessProbe`; `envFrom` gets populated into `envs` in `container`.

Right now this **population** happens in functions like `populateVolumes`, `populateContainerHealth` and one in `envFrom` which currently in PR review is [`populateContainerHealth`](https://github.com/kedgeproject/kedge/pull/84/files#diff-0f611a36f4697b86a7a093067f187692R292).

Why put all this data in the `podSpec` you might ask, because once this canonical `podSpec` is created we can simply give it to any controller that needs `podSpec` and since all the data is already *validated*, *defaulted* and *populated* in one place we don't need to do anything after that. You can see this happening in code right now where `deployment` is created:

```go
deploymentSpec.Template.Spec = app.PodSpec
```
goto code [here](https://github.com/kedgeproject/kedge/blob/master/pkg/transform/kubernetes/kubernetes.go#L149).

## Proposal

So I propose these changes should happen via a layer like we have right now of `defaulters` https://github.com/kedgeproject/kedge/issues/50 and `validators` https://github.com/kedgeproject/kedge/issues/49 . So creating a layer called a `populators` which does above which is already happening right now alongside conversion code.

**Comment by surajssd** [comment]
The diagram was created using https://www.draw.io/

**Comment by containscafeine** [comment]
Closing since we use populators now
